#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x597240FE94E60165 (rbtcollins@hp.com)
#
Name     : python-mock
Version  : 2.0.0
Release  : 68
URL      : http://pypi.debian.net/mock/mock-2.0.0.tar.gz
Source0  : http://pypi.debian.net/mock/mock-2.0.0.tar.gz
Source99 : http://pypi.debian.net/mock/mock-2.0.0.tar.gz.asc
Summary  : Mocking and Patching Library for Testing
Group    : Development/Tools
License  : BSD-2-Clause
Requires: python-mock-license = %{version}-%{release}
Requires: python-mock-python = %{version}-%{release}
Requires: python-mock-python3 = %{version}-%{release}
Requires: funcsigs
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pbr-legacypython
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : six

%description
mock is a library for testing in Python. It allows you to replace parts of
your system under test with mock objects and make assertions about how they
have been used.

%package license
Summary: license components for the python-mock package.
Group: Default

%description license
license components for the python-mock package.


%package python
Summary: python components for the python-mock package.
Group: Default
Requires: python-mock-python3 = %{version}-%{release}

%description python
python components for the python-mock package.


%package python3
Summary: python3 components for the python-mock package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-mock package.


%prep
%setup -q -n mock-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554327053
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-mock
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/python-mock/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-mock/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
